# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('selling', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='business',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeground.Resident'),
        ),
        migrations.AddField(
            model_name='business',
            name='tags',
            field=models.ManyToManyField(to='homeground.tags'),
        ),
    ]
