# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0002_auto_20190703_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
