# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0003_resident_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=models.ImageField(blank=True, upload_to='businesses/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='resident_image',
            field=models.ImageField(blank=True, upload_to='residents/'),
        ),
    ]
