# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0004_auto_20190703_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
